version: '2'
services:
  consul-server:
    image: consul
    container_name: consul-server
    network_mode: host
    environment:
      CONSUL_LOCAL_CONFIG: "{\"reconnect_timeout\":\"8h\"}"
      CONSUL_HTTP_ADDR: "0.0.0.0"
      SERVICE_8500_NAME: 'consul-http'
      SERVICE_8600_NAME: 'consul-dns'
    command:
    - "agent"
    - "-server"
    - "-ui"
    - "-bind=${SERVER_IP}"
    - "-bootstrap-expect=1"
    - "-client=0.0.0.0"
    - "-datacenter=loc"
    - "-domain=${CONSUL_DOMAIN}"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
    restart: unless-stopped
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    network_mode: bridge
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
    restart: unless-stopped
  registrator:
    image: gliderlabs/registrator:latest
    network_mode: host
    depends_on:
    - consul-server
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    command:
    - "consul://localhost:$CONSUL_WEB_PORT"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
    restart: unless-stopped
